version: '3.8'

services:
  postgres:
    image: postgres:15.4-alpine
    container_name: desafio_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cepdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - desafio-net

  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: desafio_wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - desafio-net

volumes:
  pgdata:

networks:
  desafio-net:
